default: &default
  adapter: postgresql
  username: ENV['DATABASE_USER']
  password: ENV['DATABASE_PASS']
  host: localhost

development:
  <<: *default
  database: pow-wow-api_development

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: pow-wow-api
